"""Local, self-hosted statistical model for measurement estimation.

Unlike `inference.py` (Gemini API wrapper), this is a real model trained on
real data — see `ml/scripts/train_measurement_model.py` for the training
pipeline (ANSUR II anthropometric survey, ~6000 subjects) and provenance.

Artifacts live in `ml/models/*.joblib` (gitignored, generated by the training
script — not present on a fresh clone until it's run). Loading is lazy and
optional: if the artifacts are missing, `is_local_model_available()` returns
False and callers fall back to another model, exactly like every other
degradation path in this service — never a blocking exception.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

import numpy as np

logger = logging.getLogger("angaly.ai_service")

MODELS_DIR = Path(__file__).resolve().parent.parent / "ml" / "models"
LOCAL_MODEL_VERSION = "local-measurement-imputer-ansur2-1.0.0"

_artifacts: dict[str, dict[str, Any]] = {}
_load_attempted = False


def _load_artifacts() -> None:
    global _load_attempted
    _load_attempted = True
    for gender, filename in (
        ("HOMME", "measurement_imputer_homme.joblib"),
        ("FEMME", "measurement_imputer_femme.joblib"),
    ):
        path = MODELS_DIR / filename
        if not path.exists():
            continue
        try:
            import joblib  # local import: optional heavy dependency

            _artifacts[gender] = joblib.load(path)
        except Exception:
            logger.exception("Failed to load local measurement model artifact %s", path)


def is_local_model_available(gender: str | None = None) -> bool:
    if not _load_attempted:
        _load_artifacts()
    if gender:
        return gender.upper() in _artifacts
    return len(_artifacts) > 0


def estimate_with_local_model(
    known_measurements: dict[str, float],
    gender: str | None,
    required_keys: list[str],
) -> tuple[dict[str, float], float]:
    """Returns (estimated_measurements, confidence) for the requested keys
    using the trained IterativeImputer for the given gender (defaults to
    FEMME if unspecified — matches the wizard's default). Raises if no
    artifact is available; callers must check `is_local_model_available`
    first (mirrors the fallback pattern used throughout this service)."""
    if not _load_attempted:
        _load_artifacts()

    resolved_gender = (gender or "FEMME").upper()
    artifact = _artifacts.get(resolved_gender)
    if artifact is None:
        raise RuntimeError(f"No local model artifact loaded for gender={resolved_gender!r}")

    imputer = artifact["imputer"]
    columns: list[str] = artifact["columns"]
    mae_by_key: dict[str, float] = artifact.get("mae_by_key", {})

    row = np.full(len(columns), np.nan)
    for key, value in known_measurements.items():
        if key in columns:
            row[columns.index(key)] = value

    predicted = imputer.transform(row.reshape(1, -1))[0]

    estimated: dict[str, float] = {}
    confidences: list[float] = []
    for key in required_keys:
        if key not in columns or key in known_measurements:
            continue
        value = float(predicted[columns.index(key)])
        estimated[key] = round(value, 1)
        mae = mae_by_key.get(key, 3.0)
        # Held-out MAE -> a conservative, always-indicative confidence
        # (never presented as a real measurement — spec §18).
        confidences.append(max(0.1, min(0.6, 1 - mae / 10)))

    confidence = round(sum(confidences) / len(confidences), 2) if confidences else 0.0
    return estimated, confidence
